### ISSUE TITLE
Fabric framework not found

### ISSUE THREAD

**Issue by szabolcssztanyi** [stanwood/Stanwood_Analytics_iOS#18]
Followed instructions on how to install the framework, but I keep getting this linker issue. 

<img width="1052" alt="screen shot 2018-03-21 at 7 17 53" src="https://user-images.githubusercontent.com/11644682/37696577-09f7d80a-2cd8-11e8-9399-39f5a114decf.png">

**Comment by ronanociosoig** [comment]
This was an application configuration issue.
